# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "pulp1" => "192.168.37.10",
  "pulp2" => "192.168.37.11",
  "pulp3" => "192.168.37.12"
}




Vagrant.configure("2") do |config|
  hosts.each do |name, ip|
    config.vm.define name do |machine|
    config.vm.synced_folder "../../devel", "/home/vagrant/devel"
      machine.vm.box = "bento/fedora-22"
      machine.vm.hostname = "%s.example.org" % name
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
          v.name = name
          v.customize ["modifyvm", :id, "--memory", 600]
      end
    end
  end
end

