---
- name: restart sshd
  service: name=sshd state=restarted

- name: init db
  command: pulp-manage-db
  become_user: apache
  become_method: sudo

- name: restart server services
  service: name={{ item }} state=restarted
  with_items:
    - httpd
    - pulp_workers
    - pulp_celerybeat
    - pulp_resource_manager
