- hosts: all
  become: yes
  become_user: root
  remote_user: vagrant

  handlers:

    - name: restart mongod
      service: name=mongod state=restarted


  tasks:

    - name: Download Repo Definitions
      get_url: url=https://repos.fedorapeople.org/repos/pulp/pulp/fedora-pulp.repo dest=/etc/yum.repos.d/fedora-pulp.repo mode=0644

    - name: install yum
      dnf: name=yum state=installed

    - name: Install mongodb packages
      dnf: name={{ item }} state=present
      with_items:
        - mongodb
        - mongodb-server

    - name: Disable MongoDB journal (64bit)
      lineinfile:
        backrefs: yes
        dest: /etc/mongod.conf
        regexp: "^#nojournal = false"
        line: "nojournal = true"
      notify: restart mongod

    - name: Start mongodb and enable it
      service: name=mongod state=started enabled=yes

    - name: Install qpid packages
      dnf: name={{ item }} state=present
      with_items:
      - qpid-cpp-client
      - qpid-cpp-server
      - qpid-cpp-server-linearstore
      - qpid-tools

    - name: Start and enable qpid services
      service: name={{ item }} state=started enabled=yes
      with_items:
      - qpidd

    - name: Install Pulp server, task workers and dependecies
      dnf: name=pulp-server state=present

    - name: Install and enable pulp workers
      service: name={{ item }} state=started enabled=yes
      with_items:
      - pulp_workers
      - pulp_celerybeat
      - pulp_resource_manager


    - name: Final greeting
      pause: prompt="Don't worry about all the red above; if you made it here, your Vagrant VMs are probably fine ! Please press [Enter]"
